---
title: Post-Election Campaign Analysis
author: Shriya Yarlagadda
date: '2024-12-09'
slug: post-election-campaign-analysis
categories: []
tags: []
---

In my final blog post, I analyze the Trump and Harris 2024 Presidential campaigns in the state of Michigan, one of the seven swing states that were said to have driven the outcome of the election (1).

## 1) Michigan Overview

*Geography and Electoral History*

Located in the American Midwest, among a group of states that have been termed as the Rust Belt due to their historical affiliation with American manufacturing, Michigan was identified relatively early in the election cycle as a state to watch (2). The state has historically been referred to as part of the "Blue Wall," a grouping that also includes other swing states like Pennsylvania and Wisconsin -- referencing their recent history of voting for Democratic presidential candidates, at least until Trump's election to the presidency in 2016 (3). Although the Democratic party had achieved significant electoral success in the state in recent years, holding both federal Senate seats, the governorship, and control of both state legislatures (prior to this election) and presided over a ballot measure protecting abortion access, the state's Republican party also appeared poised to make electoral progress in the 2024 election (4).

*Demographics*

Although the state has a higher percentage of White voters and a lower percentage of Latinx voters than the national average, its population has rather heterogenous political views (5). One especially prominent narrative in this election related to the state's Arab community, especially in the Detroit suburbs of Dearborn and Hamtramck, which has expressed deep discontent with the Biden administration and its policies towards the ongoing Israel-Hamas War, despite "overwhelmingly" supporting him in 2020 (6). However, scholars have also highlighted the role of other demographic groups in the state's electoral outcome, including both Latinx and Black voters (7). In particular, Harris appeared to have significantly lower polling support from Black Michigan voters than Biden did in 2020 (8). The trend also appeared reflected in pre-election polls of younger voters (8).

*Down-Ballot Candidates*

The most prominent down-ballot race in Michigan in 2024 was the state's Senate election, with US Representative Elissa Slotkin running against former Representative Mike Rogers (8). Furthermore, the state also noted several incredibly competitive US Representatives elections, including in the state's 8th District (8). However, there has also been significant engagement and fundraising efforts from both parties even at the State office level, especially given the Democrats' win of both state legislatures and the governorship in 2022 (9).

# 2) Forecasted vs Actual Outcome

My model, as described in previous blog posts, predicted that Harris would win Michigan in the 2024 Presidential election, earning a total of 51.27% of the vote, while predicting Trump would earn just 43.89%. While this skew towards Harris appeared very strong, other election experts predicted the same outcome, with FiveThirtyEight claiming that Harris would win the state 61 out of 100 times in its final prediction, Nate Silver predicting that Harris would win Michigan by over one percentage point, and the Economist predicting that she would earn upwards of 60% of the vote (10). 

However, the Trump campaign significantly outperformed these expectations, winning the state by nearly 1.5 percentage point, suggesting that many of these models, including those by prominent experts, were broadly inaccurate (11). The Republican party also experienced success at the state level, gaining control of the state House of Representatives (12). It is especially notable that although both my model and the Economist's model predicted that Harris would win a plurality of the votes, Trump only earned about 49.7% of the vote (13). This would suggest that that although these models certainly predicted the wrong winner, they showed an election that was far less competitive than the election truly was. While the other models may not have suggested such a lopsided outcome, they still seemed to have a point estimate that predicted the incorrect outcome (14). 

# 3) The Campaigns

Especially given the competitiveness of the state, both the Trump and Harris campaigns had significant engagement in Michigan (15). Levin counts 83 visits from both candidates and their vice presidential candidates (largely focused in southeast Michigan near Detroit) and the Wesleyan Media Project noted significant ad spending by both candidates in the Detroit media market (although relatively higher for the Harris campaign) (16). The candidates had several similarities in their strategies, recognizing that there may be groups of voters that have a relatively low chance of voting for them, but prioritizing outreach to key demographics they felt could turn the campaign in their favor (17). However, I analyze some key differences in their approaches and messages below.

*Harris Campaign*

Harris' campaign placed a significant emphasis on the "ground game", with campaign goals broadly focused on increasing turnout, especially early turnout, in key demographics, with the campaign ultimately noting that they saw their "path to victory" through gaining support from typically Republican suburban voters, those with a college education, women, and Black voters (18). In doing so, the campaign facilitated engagement efforts throughout the state through its 52 offices, ending with a focus on college campuses, as well as a wide-reaching advertisement strategy that outspent the Trump campaign (19).

One especially salient message for the campaign was its frequent emphasis on protecting abortion access, including in a section of one of her final speeches in Michigan that gained rousing applause from one of her key demographics -- young voters (20). However, commentators on both sides of the aisle expressed concern that this message would not be effective in Michigan, given that the state had already protected access to abortion within its borders (21). This led some members of the state legislature to instead emphasize other forms of healthcare that they perceived as being threatened, including access to IVF, perhaps in an attempt to reanimate voters motivated by the goal of protecting bodily autonomy (22).

The Harris campaign also included messages emphasizing its platform on manufacturing, with Harris even making a speech from a semiconductor factory in Michigan's Saginaw County that the Biden administration supported through funding from the CHIPS and Science Act (23). Furthermore, the campaign specifically engage with Black voters, unveiling economic plans  "appealing to Black voters" before Harris joined Charlamagne tha God for a town hall in Detroit (24).

Finally, the campaign also targeted Michigan's Arab American population, seeking to regain support despite the Biden administration's policies towards Israel (25). Although her campaign platform itself did not appear to shift significantly from Biden's policy, Harris made specific references to the conflict in her final remarks in the state and aimed to engage with Arab American community leaders (26). While this engagement arguably did result in some successes, with the prominent "Uncommitted" movement inching towards supporting her candidacy in the weeks prior to the election, the campaign also appeared to recognize that this key demographic would likely not be broadly swayed to vote for Harris, thus seeking to engage other demographics instead (27). This perhaps reflects broader criticism of the campaign, especially after the election, that argued that that the campaign failed to mobilize key supporters (28). 

*Trump Campaign*

Compared to the Harris campaign, the Trump campaign appeared to invest fewer resources into building up a "ground game" and spending on advertisements in Michigan (29). This may also have been affected by the relative discord within the Michigan Republican party, which despite claiming that it was uniting behind Trump, has experienced discord in recent years (30). Neverthless, it appeared to target some demographics of voters who it saw the Harris campaign as alienating, including Arab and Black voters (31). One common refrain among strategists was the campaign's focus on "low propensity voters" -- those who were not already motivated to turn out to vote -- by highlighting the prominent issues of "inflation and immigration" (32). Furthermore, the campaign sought to focus on maintaining its standard base (33).

Although its strategists remained concerned that it was not widespread enough, the Trump campaign's ground game was notably bolstered by external groups, including Elon Musk's America PAC (34). Interestingly, Michigan state senator Mallory McMorrow noted that her first engagement with "a live human knocking on doors for Republicans" involved meeting a canvasser who was a Democrat, but worked for Musk's PAC because of the financial benefits that he offered for doing so (34). In this case, such canvassers may be even worse "agents" for the campaign than the volunteers that Enos and Hersh analyze (35). However, it also focused on alternatives to on-the-ground engagement, notably including participation in podcasts (34).

Within Michigan, Trump also emphasized the topic of manufacturing, seeking to sway the support of traditionally Democratic-leaning union leaders, suggesting that the Harris administration would adopt electric vehicle policies that would be harmful to the state's automotive industry (36). However, the Trump campaign also aimed to capitalize on the state's Arab community's discontent with the Biden administration, with several visits to Detroit suburbs with significant Arab populations (37). This even resulted in endorsements from some community leaders -- many of whom also refused to endorse Harris (37).

# 4) Modeling the Campaigns

While some have claimed that Michigan's electoral outcome -- as well as that of other states -- indicate that fundamentals are vital, both campaigns' strategies in mobilizing can be analyzed through Vavreck's theory on campaign messaging (38). For example, we could argue that Harris ran an "insurgent" campaign by highlighting the topic of abortion (as we discussed in class) -- a topic for which the Trump campaign was "constrained" by previous views (39). Furthermore, although not following Vavreck's typology's specific focus on economic performance to decide whether a candidate runs a clarifying or insurgent campaign (another topic brought up in our course discussion), we could argue that Trump ran an "insurgent" campaign highlighting how his policy on Gaza may differ from Harris' proposals (40). 

However, a particularly interesting conclusion from this work is that the Harris campaign's comparatively strong ground game may not have been enough to sway the election in her favor (41). There are several ways to interpret this finding. On one hand, one may assume that this suggests that the ground game is not effective, perhaps aligning with the broad conclusions of work by Kalla and Broockman (42). Yet, the fact that Michigan reported incredibly high rates of turnout may suggest that the ground game was actually instrumental in the Harris campaign, preventing an even greater loss than what would have been expected if only considering the "fundamentals" -- another point discussed in our course (43). This view would align more closely with the findings of Enos & Fowler and Darr & Levendusky (44). This view could ultimately suggest that campaigns do have a significant effect on outcomes -- one that modeling can continually strive to account for.
# References

(1) Eg: Boyce, Lily, Lazaro Gamio, Eli Murray, and Alicia Parlapiano. 2024. “Tracking the Swing States for Harris and Trump.” The New York Times, August 14, 2024, sec. U.S. <https://www.nytimes.com/interactive/2024/us/elections/presidential-election-swing-states.html>. Davis Jr., Elliott. n.d. “7 States That Could Sway the 2024 Presidential Election.” US News & World Report. Accessed October 22, 2024. //www.usnews.com/news/elections/articles/7-swing-states-that-could-decide-the-2024-presidential-election; Perry, Kati, Dan Keating, and Aaron Blake. 2024. “A Guide to the 7 Battleground States That Could Swing the Election.” Washington Post. October 21, 2024. <https://www.washingtonpost.com/elections/interactive/2024/2024-swing-states-trump-harris/>.

(2) Eg: Boyce, Lily, Lazaro Gamio, Eli Murray, and Alicia Parlapiano. 2024. “Tracking the Swing States for Harris and Trump.” The New York Times, August 14, 2024, sec. U.S. <https://www.nytimes.com/interactive/2024/us/elections/presidential-election-swing-states.html>.; Crowley, Kinsey. 2024. “What States Are in the ‘Rust Belt’? What to Know on Election Night.” November 5, 2024. <https://www.usatoday.com/story/news/politics/elections/2024/11/05/rust-belt-states/76082439007/>.

(3) Eg: Buchman, Cassie, and Damita Menezes. 2024. “Can Kamala Harris Win the ‘Blue Wall’?” NewsNation. November 5, 2024. <https://www.newsnationnow.com/politics/2024-election/what-is-democratic-blue-wall/>.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Levin, Scott. 2024. “Trump, Harris Visited Michigan about 50 Times. Here’s a Map of Each Stop.” Mlive. November 4, 2024. https://www.mlive.com/politics/2024/11/trump-harris-visited-michigan-about-50-times-heres-a-map-of-each-stop.html.
; Levy, Marc, Humera Lodhi, and Parker Kaufmann. 2024. “Trump Rebuilds Democrats’ ‘blue Wall’ States with Red Bricks. Especially Pennsylvania.” AP News. November 8, 2024. <https://apnews.com/article/election-2024-pennsylvania-republicans-trump-mccormick-blue-wall-michigan-wisconsin-211cf863c602028d80c54bceb237bb2f>. “Michigan Election Results 2024: Live Updates.” n.d. NPR. Accessed December 9, 2024. <https://apps.npr.org/2024-election-results/michigan.html>. Roose, Colin. 2024. “Local Political Analyst Explains Why Michigan Went Red in 2024 Election.” WWMT. November 6, 2024. <https://wwmt.com/news/local/michigan-red-donald-trump-political-analyst-2024-election-harris-voters-economy-incumbent-polls>.

(4) Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. <https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576>. “U.S. Senate: States in the Senate \| Michigan.” n.d. Accessed December 9, 2024. <https://www.senate.gov/states/MI/intro.htm>.

(5) “The 2024 Presidential Battleground: Inside Michigan \| PRRI.” 2024. PRRI \| At the Intersection of Religion, Values, and Public Life. (blog). July 9, 2024. <https://www.prri.org/spotlight/the-2024-presidential-battleground-inside-michigan/>.

(6) “Ask the Experts: Breaking down the 2024 Presidential and Michigan Statewide Election Results.” 2024. MSUToday | Michigan State University. November 25, 2024. https://msutoday.msu.edu/news/2024/ask-the-experts-breaking-down-the-2024-election-results.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Han, Jeongyoon, and Dan Gonyea. 2023.“In Michigan, Where Every Vote Counts, Arab Americans Are Turning Away from Biden.” NPR, November 17, 2023, sec. Middle East crisis — explained. <https://www.npr.org/2023/11/17/1213668804/arab-americans-michigan-voters-biden-israel-hamas-palestinians>. ; Harb, Ali. 2024. “Why Many Arab Voters in Michigan Are Flocking to Trump Ahead of US Election \| US Election 2024 News \| Al Jazeera.” November 2, 2024. <https://www.aljazeera.com/news/2024/11/2/why-many-arab-voters-in-michigan-are-flocking-to-trump-ahead-of-us-election>.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Perkins, Tom. 2024. “‘They Blew It’: Democrats Lost 22,000 Votes in Michigan’s Heavily Arab American Cities.” *The Guardian*, November 9, 2024, sec. US news. <https://www.theguardian.com/us-news/2024/nov/09/democrats-lose-michigan-arab-american-voters>.

(7) “Ask the Experts: Breaking down the 2024 Presidential and Michigan Statewide Election Results.” 2024. MSUToday | Michigan State University. November 25, 2024. https://msutoday.msu.edu/news/2024/ask-the-experts-breaking-down-the-2024-election-results.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.

(8) Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.

(9) Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576

(10) Morris, G. Elliott. 2024. “Who Is Favored To Win The 2024 Presidential Election? | FiveThirtyEight.” FiveThirtyEight. November 5, 2024. https://projects.fivethirtyeight.com/2024-election-forecast/.; Silver, Nate. n.d. “FINAL Silver Bulletin 2024 Presidential Election Forecast.” Accessed December 9, 2024. https://www.natesilver.net/p/nate-silver-2024-president-election-polls-model.; The Economist. n.d. “Kamala Harris Moves Ahead—Just—in Our Final Election Forecast.” Accessed December 9, 2024. https://www.economist.com/united-states/2024/11/05/kamala-harris-moves-ahead-just-in-our-final-election-forecast.

(11) “Michigan Election Results 2024: Live Updates.” n.d. NPR. Accessed December 9, 2024. https://apps.npr.org/2024-election-results/michigan.html.; Morris, G. Elliott. 2024. “2024 Polls Were Accurate but Still Underestimated Trump - ABC News.” November 8, 2024. https://abcnews.go.com/538/2024-polls-accurate-underestimated-trump/story?id=115652118.


(12) Eg: “Ask the Experts: Breaking down the 2024 Presidential and Michigan Statewide Election Results.” 2024. MSUToday | Michigan State University. November 25, 2024. https://msutoday.msu.edu/news/2024/ask-the-experts-breaking-down-the-2024-election-results.

(13) “Michigan Election Results 2024: Live Updates.” n.d. NPR. Accessed December 9, 2024. https://apps.npr.org/2024-election-results/michigan.html.; The Economist. n.d. “Kamala Harris Moves Ahead—Just—in Our Final Election Forecast.” Accessed December 9, 2024. https://www.economist.com/united-states/2024/11/05/kamala-harris-moves-ahead-just-in-our-final-election-forecast  


(14) Morris, G. Elliott. 2024. “Who Is Favored To Win The 2024 Presidential Election? | FiveThirtyEight.” FiveThirtyEight. November 5, 2024. https://projects.fivethirtyeight.com/2024-election-forecast/.; Silver, Nate. n.d. “FINAL Silver Bulletin 2024 Presidential Election Forecast.” Accessed December 9, 2024. https://www.natesilver.net/p/nate-silver-2024-president-election-polls-model

(15) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Becker, Amanda. 2024. “Women Know How to Win in Michigan. Now They’re Helping Harris.” The 19th. October 30, 2024. https://19thnews.org/2024/10/michigan-women-democrats-win-helping-harris/.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Levin, Scott. 2024. “Trump, Harris Visited Michigan about 50 Times. Here’s a Map of Each Stop.” Mlive. November 4, 2024. https://www.mlive.com/politics/2024/11/trump-harris-visited-michigan-about-50-times-heres-a-map-of-each-stop.html.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.

(16) Levin, Scott. 2024. “Trump, Harris Visited Michigan about 50 Times. Here’s a Map of Each Stop.” Mlive. November 4, 2024. https://www.mlive.com/politics/2024/11/trump-harris-visited-michigan-about-50-times-heres-a-map-of-each-stop.html.; Wesleyan Media Project. 2024a. “Harris TV Ads Plummet Before Rebounding - Wesleyan Media Project.” October 24, 2024. https://mediaproject.wesleyan.edu/releases-102424/.; ———. 2024b. “Pro-Trump TV Ads Plummet in Past Two Weeks as Harris Expands Ad Advantage Across Platforms - Wesleyan Media Project.” September 26, 2024. https://mediaproject.wesleyan.edu/releases-092624/.


(17) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” December 6, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever.


(18) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-ground-game/.

(19) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-ground-game/.;  Popli, Nik. 2024. “Harris Pitches Positive Closing Message in Michigan.” TIME. November 4, 2024. https://time.com/7171844/harris-pitches-positive-closing-message-in-michigan/.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” December 6, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever.; Wesleyan Media Project. 2024a. “Harris TV Ads Plummet Before Rebounding - Wesleyan Media Project.” October 24, 2024. https://mediaproject.wesleyan.edu/releases-102424/.; ———. 2024b. “Pro-Trump TV Ads Plummet in Past Two Weeks as Harris Expands Ad Advantage Across Platforms - Wesleyan Media Project.” September 26, 2024. https://mediaproject.wesleyan.edu/releases-092624/.


(20) Eg: Becker, Amanda. 2024. “Women Know How to Win in Michigan. Now They’re Helping Harris.” The 19th. October 30, 2024. https://19thnews.org/2024/10/michigan-women-democrats-win-helping-harris/.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576.; Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Superville, Darlene, Bill Barrow, and Isabella Volmert. 2024. “Election 2024: Harris Rallies across Michigan, Promises ‘a New Way Forward’ | AP News.” AP News. November 3, 2024. https://apnews.com/article/kamala-harris-donald-trump-election-day-2024-presidential-race-14d9d96cecdab90ebc2a4c31e8ccf47f.

(21) Eg: Becker, Amanda. 2024. “Women Know How to Win in Michigan. Now They’re Helping Harris.” The 19th. October 30, 2024. https://19thnews.org/2024/10/michigan-women-democrats-win-helping-harris/.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576.; Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.

(22) Eg: Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.

(23) Eg: Picciotto, Rebecca. 2024. “Harris Focuses on Manufacturing Plan in Michigan as Trump Leads on Economy.” CNBC. October 28, 2024. https://www.cnbc.com/2024/10/28/harris-trump-election-manufacturing-proposals-battleground-michigan.html.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.

(24) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.

(25) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Harb, Ali. 2024. “Why Many Arab Voters in Michigan Are Flocking to Trump Ahead of US Election | US Election 2024 News | Al Jazeera.” November 2, 2024. https://www.aljazeera.com/news/2024/11/2/why-many-arab-voters-in-michigan-are-flocking-to-trump-ahead-of-us-election.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.

(26) Eg: Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Superville, Darlene, Bill Barrow, and Isabella Volmert. 2024. “Election 2024: Harris Rallies across Michigan, Promises ‘a New Way Forward’ | AP News.” AP News. November 3, 2024. https://apnews.com/article/kamala-harris-donald-trump-election-day-2024-presidential-race-14d9d96cecdab90ebc2a4c31e8ccf47f.


(27) Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.;Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Weisman, Jonathan. 2024. “Pro-Palestinian ‘Uncommitted’ Group Comes Out Firmly Against Trump.” The New York Times, October 8, 2024, sec. U.S. https://www.nytimes.com/2024/10/08/us/politics/palestine-uncommitted-trump.html.

(28) Eg: “Ask the Experts: Breaking down the 2024 Presidential and Michigan Statewide Election Results.” 2024. MSUToday | Michigan State University. November 25, 2024. https://msutoday.msu.edu/news/2024/ask-the-experts-breaking-down-the-2024-election-results.
Roose, Colin. 2024. “Local Political Analyst Explains Why Michigan Went Red in 2024 Election.” WWMT. November 6, 2024. https://wwmt.com/news/local/michigan-red-donald-trump-political-analyst-2024-election-harris-voters-economy-incumbent-polls.

(29) Eg: Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Lee, Michael. 2024. “‘Massive and Professional’ Effort Boosts GOP’s Confidence about Ground Game in Pivotal Swing State.” Text.Article. Fox News. Fox News. October 16, 2024. https://www.foxnews.com/politics/massive-professional-effort-boosts-gops-confidence-about-ground-game-pivotal-swing-state.; Messerly, Megan, Natalie Allison, and Elena Schneider. 2024. “Republicans Are Starting to Raise Alarms about Trump’s Ground Game - POLITICO.” POLITICO. September 30, 2024. https://www.politico.com/news/2024/09/30/republicans-alarm-trump-ground-game-00181577.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-ground-game/.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.

(30) Eg: Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576.; Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.

(31) Eg: Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” December 6, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.

(32) Eg: Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Lee, Michael. 2024. “‘Massive and Professional’ Effort Boosts GOP’s Confidence about Ground Game in Pivotal Swing State.” Text.Article. Fox News. Fox News. October 16, 2024. https://www.foxnews.com/politics/massive-professional-effort-boosts-gops-confidence-about-ground-game-pivotal-swing-state.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-ground-game/.

(33) Eg: Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.


(34) Eg: Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Lahut, Jake. n.d. “Donald Trump’s Ground Game in Michigan Is Mostly Glitchy Apps and Vibes.” Wired. Accessed December 9, 2024. https://www.wired.com/story/donald-trump-kamala-harris-michigan/.; Messerly, Megan, Natalie Allison, and Elena Schneider. 2024. “Republicans Are Starting to Raise Alarms about Trump’s Ground Game - POLITICO.” POLITICO. September 30, 2024. https://www.politico.com/news/2024/09/30/republicans-alarm-trump-ground-game-00181577.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-g3round-game/.

(35) Enos, Ryan D., and Eitan D. Hersh. 2015. “Party Activists as Campaign Advertisers: The Ground Campaign as a Principal-Agent Problem.” American Political Science Review 109 (2): 252–78. https://doi.org/10.1017/S0003055415000064.

(36) Eg: Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Picciotto, Rebecca. 2024. “Harris Focuses on Manufacturing Plan in Michigan as Trump Leads on Economy.” CNBC. October 28, 2024. https://www.cnbc.com/2024/10/28/harris-trump-election-manufacturing-proposals-battleground-michigan.html.; Ward, Myah. 2024. “‘It’s Not Won’: Democrats Jittery over Razor-Thin Race in Michigan.” POLITICO. October 5, 2024. https://www.politico.com/news/2024/10/05/kamala-harris-michigan-battleground-2024-00182614.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” November 5, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever.

(37) Eg: Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Harb, Ali. 2024. “Why Many Arab Voters in Michigan Are Flocking to Trump Ahead of US Election | US Election 2024 News | Al Jazeera.” November 2, 2024. https://www.aljazeera.com/news/2024/11/2/why-many-arab-voters-in-michigan-are-flocking-to-trump-ahead-of-us-election.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” November 5, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever.

(38) Enos, Ryan. 2024. “Assessing Campaigns.” Presented at the GOV 1347, December 3.; Roose, Colin. 2024. “Local Political Analyst Explains Why Michigan Went Red in 2024 Election.” WWMT. November 6, 2024. https://wwmt.com/news/local/michigan-red-donald-trump-political-analyst-2024-election-harris-voters-economy-incumbent-polls.; Vavreck, Lynn. 2009. The Message Matters: The Economy and Presidential Campaigns. Princeton: Princeton University Press. https://muse.jhu.edu/pub/267/monograph/book/36264. 

(39) Eg: Becker, Amanda. 2024. “Women Know How to Win in Michigan. Now They’re Helping Harris.” The 19th. October 30, 2024. https://19thnews.org/2024/10/michigan-women-democrats-win-helping-harris/.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456.; Crampton, Liz. 2024. “Democrats Won Complete Power in Michigan. Republicans Are Trying to Take It Away.” POLITICO. September 25, 2024. https://www.politico.com/news/2024/09/25/michigan-state-legislature-democrats-republicans-00180576.; Enos, Ryan. 2024. “Assessing Campaigns.” Presented at the GOV 1347, December 3.; Mahtesian, Charlie. 2024. “What the Campaign Feels like in Michigan.” POLITICO. October 8, 2024. https://www.politico.com/newsletters/politico-nightly/2024/10/08/what-the-campaign-feels-like-in-michigan-00182969.; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Vavreck, Lynn. 2009. The Message Matters: The Economy and Presidential Campaigns. Princeton: Princeton University Press. https://muse.jhu.edu/pub/267/monograph/book/36264. 

(40) Eg:  Contorno, Steve, and Fredreka Schouten. 2024. “Trump’s Ground Game Relies on Untraditional Strategies to Draw out Battleground Voters | CNN Politics.” CNN. October 4, 2024. https://www.cnn.com/2024/10/04/politics/trump-campaign-ground-game/index.html.; Enos, Ryan. 2024. “Assessing Campaigns.” Presented at the GOV 1347, December 3.; Harb, Ali. 2024. “Why Many Arab Voters in Michigan Are Flocking to Trump Ahead of US Election | US Election 2024 News | Al Jazeera.” November 2, 2024. https://www.aljazeera.com/news/2024/11/2/why-many-arab-voters-in-michigan-are-flocking-to-trump-ahead-of-us-election.; Vavreck, Lynn. 2009. The Message Matters: The Economy and Presidential Campaigns. Princeton: Princeton University Press. https://muse.jhu.edu/pub/267/monograph/book/36264.; Schuster, Simon D. 2024. “Donald Trump Caps Campaign in Michigan, Predicting ‘Greatest Victory’ Ever | Bridge Michigan.” November 5, 2024. https://www.bridgemi.com/michigan-government/donald-trump-caps-campaign-michigan-predicting-greatest-victory-ever. 

(41)  Alvarez, Priscilla. 2024. “Harris Advisers Zero in on Michigan Strategy to Overcome Anticipated Losses among Some Parts of Democratic Coalition | CNN Politics.” CNN. October 14, 2024. https://www.cnn.com/2024/10/14/politics/harris-michigan-strategy/index.html.; Burton, Cooper. 2024. “Black and Arab American Voters Could Swing Michigan’s 2024 Election.” ABC News. October 3, 2024. https://abcnews.go.com/538/black-arab-american-voters-swing-michigans-2024-election/story?id=114428456; Navarro, Aaron, and Nidia Cavazos. 2024. “In Michigan, Harris Campaign Sees Path to Victory Going through the Suburbs - CBS News.” October 17, 2024. https://www.cbsnews.com/news/kamala-harris-michigan-campaign-suburbs/.; Navarro, Aaron, Olivia Rinaldi, and Jacob Rosen. 2024. “In Closing Days, Harris Leans on Ground Game Advantage as Outside Groups Bolster Trump’s Voter Mobilization - CBS News.” October 24, 2024. https://www.cbsnews.com/news/harris-trump-2024-election-ground-game/.; Michigan Election Results 2024: Live Updates.” n.d. NPR. Accessed December 9, 2024. https://apps.npr.org/2024-election-results/michigan.html.

(42) Kalla, Joshua L., and David E. Broockman. 2018. “The Minimal Persuasive Effects of Campaign Contact in General Elections: Evidence from 49 Field Experiments.” American Political Science Review 112 (1): 148–66. https://doi.org/10.1017/S0003055417000363.

(43) Enos, Ryan. 2024. “Assessing Campaigns.” Presented at the GOV 1347, December 3.

(44) Darr, Joshua P., and Matthew S. Levendusky. 2014. “Relying on the Ground Game: The Placement and Effect of Campaign Field Offices.” American Politics Research 42 (3): 529–48. https://doi.org/10.1177/1532673X13500520.;Enos, Ryan D., and Anthony Fowler. 2018. “Aggregate Effects of Large-Scale Campaigns on Voter Turnout.” Political Science Research and Methods 6 (4): 733–51. https://doi.org/10.1017/psrm.2016.21.



